[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 5000

[window]
title = "Alacritty"
# option_as_alt = "Both" # (macos only)
opacity = 0.7
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = ["/Users/tom/.config/alacritty/dracula.toml"]

