version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tom.gla@seznam.cz
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"
