#!/bin/bash

PC=$(hostname)

if [[ $PC == "Manjaro-Airbook" ]];
then
	TEMP_RAW=$(sensors | head -n 13 | tail -n 1 | sed -n "s/.*+\(.*C\) .*/\1/p")
else
	TEMP_RAW=$(sensors | head -n 5 | tail -n 1 | sed -n "s/.*+\(.*C\) .*/\1/p")
fi

echo "${TEMP_RAW}"
echo "${TEMP_RAW}"

TEMP_ROUND=${TEMP_RAW%.*}

if (( $(echo "$TEMP_ROUND > 75" | bc -l) ))
then
	echo "#FF6666"
elif (( $(echo "$TEMP_ROUND > 60" | bc -l) ))
then
	echo "#FFBF00"
else
	echo "#33CC33"
fi
