let g:coc_global_extensions = [
			\'coc-json',
			\'coc-git',
			\'coc-python',
			\'coc-java',
			\'coc-html',
			\'coc-css',
			\'coc-phpls',
			\'coc-xml',
			\'coc-yaml',
			\'coc-clangd',
			\'coc-sh',
			\'coc-discord-rpc',
			\'coc-highlight',
			\'coc-diagnostic',
			\'coc-markdownlint',
			\'coc-pairs',
			\]
