- name: Fetch Kubernetes config from remote server to local and replace server IP
  hosts: server
  vars:
    remote_kubeconfig: /etc/rancher/k3s/k3s.yaml
    local_kubeconfig: ~/.kube/config
    tmp_kubeconfig: "/tmp/kubeconfig_{{ inventory_hostname }}"

  tasks:
    - name: Fetch kubeconfig from remote server
      become: true
      fetch:
        src: "{{ remote_kubeconfig }}"
        dest: "{{ tmp_kubeconfig }}"
        flat: yes

    - name: Replace server IP in kubeconfig with remote host IP
      delegate_to: localhost
      replace:
        path: "{{ tmp_kubeconfig }}"
        regexp: "server: https://.*:6443"
        replace: "server: https://{{ hostvars[inventory_hostname]['ansible_host'] }}:6443"

    - name: Copy updated kubeconfig to local machine default location
      delegate_to: localhost
      copy:
        src: "{{ tmp_kubeconfig }}"
        dest: "{{ local_kubeconfig }}"
        mode: '0600'
        force: true

    - name: Clean up temporary kubeconfig file
      delegate_to: localhost
      file:
        path: "{{ tmp_kubeconfig }}"
        state: absent
