- name: Initial server setup
  hosts: server
  become: true
  vars:
    user_name: "glazrtom"
    hostname: "orangepi"
  vars_prompt:
    - name: user_password
      prompt: "Enter password for the new user ({{ user_name }})"
      private: yes
  tasks:
    - name: Ensure user exists
      user:
        name: "{{ user_name }}"
        uid: 1001
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
        create_home: yes
        groups: sudo
        append: yes
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
