- name: Install docker
  hosts: all
  become: true
  vars_prompt:
    - name: dockerhub_username
      prompt: "Enter Docker Hub username (leave blank to skip Docker Hub login)"
      private: no
      default: "tomato4"
    - name: dockerhub_token
      prompt: "Enter Docker Hub token (leave blank to skip Docker Hub login)"
      private: yes
  tasks:
    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_token }}"
