- name: Setup Fastfetch
  hosts: all
  become: true
  vars:
#    fastfetch_version: "latest"
#    fastfetch_deb_url: >-
#      https://github.com/fastfetch-cli/fastfetch/releases/
#      download/{{ fastfetch_version }}/fastfetch-linux-{{ ansible_architecture }}.deb

  tasks:
    - name: Add Fastfetch PPA (Ubuntu 22.04–24.10)
      block:
        - name: Add Fastfetch PPA (Ubuntu 22.04–24.10)
          apt_repository:
            repo: ppa:zhangsongcui3371/fastfetch
            state: present
          register: fastfetch_ppa

        - name: Update apt cache after adding PPA
          apt:
            update_cache: yes
          when: fastfetch_ppa.changed
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version("22.04", ">=")
        - ansible_distribution_version is version("24.10", "<")

#      - name: Download Fastfetch .deb for other Debian/Ubuntu
#        get_url:
#          url: "{{ fastfetch_deb_url }}"
#          dest: "/tmp/fastfetch.deb"
#          mode: '0644'
#        when: (ansible_distribution in ["Ubuntu", "Debian"]) and
#          not ((ansible_distribution == "Ubuntu" and ansible_distribution_version is version("24.10", ">=")) or
#          (ansible_distribution == "Debian" and ansible_distribution_version is version("13", ">=")))
#
#      - name: Install downloaded Fastfetch .deb
#        apt:
#          deb: "/tmp/fastfetch.deb"
#          state: present
#        when: (ansible_distribution in ["Ubuntu", "Debian"]) and
#          not ((ansible_distribution == "Ubuntu" and ansible_distribution_version is version("24.10", ">=")) or
#          (ansible_distribution == "Debian" and ansible_distribution_version is version("13", ">=")))

    - name: Install Fastfetch via package manager
      package:
        name: fastfetch
        state: present
