- import_playbook: core/config_dir.yml

- name: Setup Neovim
  hosts: all
  vars:
    path_autoload: "{{ path_local }}/share/nvim/site/autoload"
  tasks:
    - name: Install Neovim
      become: true
      package:
        name: neovim
        state: present

    - name: Link neovim config
      file:
        src: "{{ path_dotfiles }}/nvim"
        dest: "{{ path_config }}/nvim"
        state: link
        force: yes

    - name: Ensure autoload directory exists
      file:
        path: "{{ path_autoload }}"
        state: directory
        mode: '0755'

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ path_autoload }}/plug.vim"
        mode: '0644'

    - name: For Debian based
      when: ansible_os_family == 'Debian'
      block:
        - name: Install Node.js and npm (Debian-based)
          become: true
          apt:
            name:
              - nodejs
              - npm
            state: present

        - name: Install python3-pip (Debian-based)
          become: true
          apt:
            name: python3-pip
            state: present

        - name: Install python3-pynvim (Debian-based)
          become: true
          apt:
            name: python3-pynvim
            state: present

        - name: Install ueberzug with pip (Debian-based)
          become: true
          apt:
            name: ueberzug
            state: present

        - name: Install python3-venv (Debian-based)
          become: true
          apt:
            name: python3-venv
            state: present

          # TODO this may be also for other systems
        - name: Install treesitter-cli (Debian-based)
          become: true
          apt:
            name: tree-sitter-cli
            state: present

    - name: Install pynvim and ueberzug with pip (non-Debian)
      pip:
        name:
          - pynvim
          - ueberzug
        executable: pip3
      when: ansible_os_family != 'Debian'

    # - name: Install Jedi language server (optional)
    #   pip:
    #     name: jedi-language-server
    #     executable: pip3
    #   when: ansible_os_family == 'Debian'
    #   # Uncomment if Jedi is needed
