- import_playbook: fastfetch.yml

- name: Setup ZSH
  hosts: all
  vars:
    name_zshrc: ".zshrc"
    name_p10k: ".p10k.zsh"
    path_zsh: "{{ path_dotfiles }}/zsh"
    path_zshrc: "{{ path_zsh }}/{{ name_zshrc }}"
    path_p10k: "{{ path_zsh }}/{{ name_p10k }}"
  tasks:
    - name: Install ZSH and dependencies
      become: true
      package:
        name:
          - zsh
          - zsh-syntax-highlighting
          - zsh-autosuggestions
          - eza
          - autojump
        state: present

    - name: Link .zshrc file
      file:
        src: "{{ path_zshrc }}"
        dest: "{{ path_home }}/{{ name_zshrc }}"
        state: link
        force: yes

    - name: Link .p10k file
      file:
        src: "{{ path_p10k }}"
        dest: "{{ path_home }}/{{ name_p10k }}"
        state: link
        force: yes

    - name: Change default shell to zsh
      become: true
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh