- name: Download homelab repository
  hosts: server
  vars:
    repo_url: "https://github.com/tomato4/homelab.git"
    repo_dest: "{{ path_home }}/homelab"
    applications_dir: "{{ repo_dest }}/applications"
  tasks:
    - name: Clone or update homelab repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: master
        update: yes
