- name: Ensure Python dependencies for Kubernetes modules are installed
  hosts: server
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python packages for k8s
      apt:
        name:
          - python3-kubernetes
          - python3-openshift
          - python3-yaml
          - python3-pip        # optional, in case pip is needed for other tasks
        state: present
