export SETUP_USER="tomato"
export SETUP_HOME="/home/$SETUP_USER"
export PROGRAMS="$SETUP_HOME/Programs"
export CONFIG="$SETUP_HOME/.config"
export DOTFILES="$SETUP_HOME/dotfiles"
export DOTFILES_SETUP="$DOTFILES/setup"
export DOTFILES_ENV_FILE="$DOTFILES_SETUP/env"
export DOTFILES_CONFIGS="$DOTFILES/configs"
export DOTFILES_I3="$DOTFILES/i3"
export DOTFILES_I3_CONFIGS="$DOTFILES_I3/configs"
export DOTFILES_I3BLOCK="$DOTFILES/i3blocks"
export DOTFILES_BASH="$DOTFILES/bash"
export DOTFILES_PROGRAMS="$DOTFILES/programs"
export DOTFILES_XKB="$DOTFILES/xkb"
export WORK_CME="$SETUP_HOME/NetBeansProjects/cme"
export DOTFILES_WORK="$DOTFILES/Work/config"

