#!bin/bash

# set default text editor
export EDITOR=/usr/bin/nvim

# set global variables
export DOTFILES=$HOME/dotfiles

# add aliases file
source ~/dotfiles/bash/tools/bash_aliases

# enable pureline plug for bash "PS1" style
source ~/Programs/pureline/pureline ~/.config/pureline/.pureline.conf
