#!bin/bash

# set default text editor
export EDITOR=/usr/bin/nvim

# set global variables
export DOTFILES=/home/tomato/dotfiles

# add aliases file
source /home/tomato/dotfiles/bash/tools/bash_aliases

# enable pureline plug for bash "PS1" style
source /home/tomato/Programs/pureline/pureline /home/tomato/.config/pureline/.pureline.conf
